algoritmo "fibonacci" // 0 1 1 2 3 5 8 13
// Função :
// Autor :
// Data : 09/02/2022
// Seção de Declarações 
var
     valor, valor1, valor2, cont : inteiro
inicio
      valor <- -1
      valor1 <- 1

      
      para cont<- 0 ate 15 faca

            valor2<- valor + valor1
            valor <- valor1
            valor1<- valor2
            escreval(valor2)
      
      fimpara
      
fimalgoritmo
