algoritmo "ParOuImparProcedimento"
// Função :
// Autor :
// Data : 09/02/2022
// Seção de Declarações 
var
    n: inteiro
    Procedimento ParOuImpar (v: inteiro)
    inicio
      se(v%2=0)entao
       escreval("O numero",v," é par")
       senao
            escreval("O numero",v," é impar")
      fimse
    FimProcedimento
inicio
      escreva("Digite um numero: ")
      leia(n)
      ParOuImpar(N)
fimalgoritmo
