algoritmo "SomadorNumerico"
// Função :
// Autor :
// Data : 06/02/2022
// Seção de Declarações 
var
    num, n, soma, maior, menor: inteiro

inicio

      num <- 1
      enquanto (num <= 5) faca
         Escreval("Digite um valor: ")
         leia(n)
            se (n > maior)entao
                maior <- n
            senao (n < menor)entao
                  menor <- n
            fimse
         soma <- soma + n
         num <- num + 1
      fimenquanto

fimalgoritmo
