algoritmo "somadorWHile"
// Função :
// Autor :
// Data : 07/02/2022
// Seção de Declarações 
var
    num, cont, soma: inteiro
inicio
      cont <- 1
      soma <- 0
      
      enquanto(cont <= 5) faca
        Escreval("Digite um valor: ")
        leia(num)
        
        soma <- soma + num
        cont <- cont + 1
        
      fimenquanto
      Escreval("a soma dos valores é, ",s)
fimalgoritmo
